//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveTimetable.Resources.Validation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HospitalTripManagerValidationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HospitalTripManagerValidationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InteractiveTimetable.Resources.Validation.HospitalTripManagerValidationStrings", typeof(HospitalTripManagerValidationStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Trip is not set..
        /// </summary>
        internal static string ArgumentIsNull {
            get {
                return ResourceManager.GetString("ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not correct hospital trip dates. There is a diagnostic that was done on {0}. So changing hospital trip dates this way will make the diagnostic to be out of hospital trip..
        /// </summary>
        internal static string DiagnosticOutOfTrip {
            get {
                return ResourceManager.GetString("DiagnosticOutOfTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date of a hospital trip can&apos;t be later or equal than the finish date..
        /// </summary>
        internal static string StartDateLaterThanFinishDate {
            get {
                return ResourceManager.GetString("StartDateLaterThanFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date period is already occupied by another trip..
        /// </summary>
        internal static string TripInsideAnotherTrip {
            get {
                return ResourceManager.GetString("TripInsideAnotherTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip in the past is not allowed..
        /// </summary>
        internal static string TripInThePast {
            get {
                return ResourceManager.GetString("TripInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id is not set..
        /// </summary>
        internal static string UserIsNotSet {
            get {
                return ResourceManager.GetString("UserIsNotSet", resourceCulture);
            }
        }
    }
}
