//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveTimetable.Resources.Repositories {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CriterionDefinitionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CriterionDefinitionStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InteractiveTimetable.Resources.Repositories.CriterionDefinitionStrings", typeof(CriterionDefinitionStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знания, представления об окружающем мире.
        /// </summary>
        public static string Criterion1 {
            get {
                return ResourceManager.GetString("Criterion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самообслуживание.
        /// </summary>
        public static string Criterion10 {
            get {
                return ResourceManager.GetString("Criterion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бытовые навыки.
        /// </summary>
        public static string Criterion11 {
            get {
                return ResourceManager.GetString("Criterion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра.
        /// </summary>
        public static string Criterion12 {
            get {
                return ResourceManager.GetString("Criterion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Взаимодействие с детьми и взрослыми.
        /// </summary>
        public static string Criterion13 {
            get {
                return ResourceManager.GetString("Criterion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммуникация.
        /// </summary>
        public static string Criterion14 {
            get {
                return ResourceManager.GetString("Criterion14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Понимание обращённой речи.
        /// </summary>
        public static string Criterion15 {
            get {
                return ResourceManager.GetString("Criterion15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наличие речи.
        /// </summary>
        public static string Criterion16 {
            get {
                return ResourceManager.GetString("Criterion16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее эмоциональное состояние ребенка.
        /// </summary>
        public static string Criterion17 {
            get {
                return ResourceManager.GetString("Criterion17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наличие дезадаптивного поведения.
        /// </summary>
        public static string Criterion18 {
            get {
                return ResourceManager.GetString("Criterion18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сенсорные эталоны (цвет).
        /// </summary>
        public static string Criterion2 {
            get {
                return ResourceManager.GetString("Criterion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сенсорные эталоны (форма).
        /// </summary>
        public static string Criterion3 {
            get {
                return ResourceManager.GetString("Criterion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сенсорные эталоны (величина).
        /// </summary>
        public static string Criterion4 {
            get {
                return ResourceManager.GetString("Criterion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количественные представления.
        /// </summary>
        public static string Criterion5 {
            get {
                return ResourceManager.GetString("Criterion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Особенности и характер познавательной дейтельности.
        /// </summary>
        public static string Criterion6 {
            get {
                return ResourceManager.GetString("Criterion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изобразительная деятельность (рисование).
        /// </summary>
        public static string Criterion7 {
            get {
                return ResourceManager.GetString("Criterion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изобразительная деятельность (лепка).
        /// </summary>
        public static string Criterion8 {
            get {
                return ResourceManager.GetString("Criterion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изобразительная деятельность (аппликация).
        /// </summary>
        public static string Criterion9 {
            get {
                return ResourceManager.GetString("Criterion9", resourceCulture);
            }
        }
    }
}
