#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InteractiveTimetable.Droid.Resource", IsApplication=true)]

namespace InteractiveTimetable.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_card_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_photo_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bluecustom_toast = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int card_frame = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int empty_new_tape_item = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int exclamation_triangle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int frame_with_black_back = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int green_round_corner_frame = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int green_tick = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int info_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int locked_icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int red_round_corner_frame = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int redcustom_toast = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int round_corner_frame = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int timetable_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int unlocked_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int users_icon = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001e
			public const int add_trip_btn = 2131034142;
			
			// aapt resource value: 0x7f050083
			public const int add_user_btn = 2131034243;
			
			// aapt resource value: 0x7f05007c
			public const int apply_changes_btn = 2131034236;
			
			// aapt resource value: 0x7f050062
			public const int apply_trip_edit_button = 2131034210;
			
			// aapt resource value: 0x7f05007b
			public const int birth_date_show = 2131034235;
			
			// aapt resource value: 0x7f050061
			public const int buttons_layout = 2131034209;
			
			// aapt resource value: 0x7f05007d
			public const int cancel_btn = 2131034237;
			
			// aapt resource value: 0x7f050063
			public const int cancel_trip_edit_button = 2131034211;
			
			// aapt resource value: 0x7f050002
			public const int card_list_item_frame = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int card_list_item_image = 2131034115;
			
			// aapt resource value: 0x7f05003a
			public const int clock = 2131034170;
			
			// aapt resource value: 0x7f050004
			public const int create_timetable_main_layout = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int ct_activity_cards = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int ct_activity_cards_divider = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int ct_activity_cards_label = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int ct_activity_cards_layout = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int ct_back_button = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ct_current_date = 2131034120;
			
			// aapt resource value: 0x7f050015
			public const int ct_goal_cards = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int ct_goal_cards_label = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int ct_goal_cards_layout = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int ct_label = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int ct_top_bar = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int ct_top_bar_divider = 2131034121;
			
			// aapt resource value: 0x7f050037
			public const int day_timetable_label = 2131034167;
			
			// aapt resource value: 0x7f050088
			public const int delete_card_button = 2131034248;
			
			// aapt resource value: 0x7f050089
			public const int delete_trip_item = 2131034249;
			
			// aapt resource value: 0x7f05008a
			public const int delete_user_item = 2131034250;
			
			// aapt resource value: 0x7f050076
			public const int edit_photo_btn = 2131034230;
			
			// aapt resource value: 0x7f050056
			public const int edit_trip_button = 2131034198;
			
			// aapt resource value: 0x7f050067
			public const int edit_user = 2131034215;
			
			// aapt resource value: 0x7f050082
			public const int empty_list = 2131034242;
			
			// aapt resource value: 0x7f05001d
			public const int empty_trip_list = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int error_message = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int error_text = 2131034136;
			
			// aapt resource value: 0x7f05007e
			public const int find_user = 2131034238;
			
			// aapt resource value: 0x7f05005f
			public const int finish_date = 2131034207;
			
			// aapt resource value: 0x7f05005e
			public const int finish_date_label = 2131034206;
			
			// aapt resource value: 0x7f05005d
			public const int finish_date_layout = 2131034205;
			
			// aapt resource value: 0x7f050060
			public const int finish_time = 2131034208;
			
			// aapt resource value: 0x7f050079
			public const int first_name_edit = 2131034233;
			
			// aapt resource value: 0x7f050041
			public const int frameLayout1 = 2131034177;
			
			// aapt resource value: 0x7f050070
			public const int frameLayout2 = 2131034224;
			
			// aapt resource value: 0x7f050065
			public const int frameLayout3 = 2131034213;
			
			// aapt resource value: 0x7f05006e
			public const int general_monitoring = 2131034222;
			
			// aapt resource value: 0x7f050040
			public const int go_and_add_button = 2131034176;
			
			// aapt resource value: 0x7f050077
			public const int gridLayout1 = 2131034231;
			
			// aapt resource value: 0x7f05001b
			public const int hospital_trip_main_content = 2131034139;
			
			// aapt resource value: 0x7f050017
			public const int imageView1 = 2131034135;
			
			// aapt resource value: 0x7f05001f
			public const int info = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int info_message = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int info_text = 2131034145;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050078
			public const int last_name_edit = 2131034232;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050071
			public const int linearLayout2 = 2131034225;
			
			// aapt resource value: 0x7f050038
			public const int linearLayout3 = 2131034168;
			
			// aapt resource value: 0x7f050072
			public const int linearLayout4 = 2131034226;
			
			// aapt resource value: 0x7f050075
			public const int linearLayout5 = 2131034229;
			
			// aapt resource value: 0x7f050073
			public const int linearLayout6 = 2131034227;
			
			// aapt resource value: 0x7f050039
			public const int lock_screen_button = 2131034169;
			
			// aapt resource value: 0x7f050024
			public const int main_landscape = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int main_portait = 2131034146;
			
			// aapt resource value: 0x7f050035
			public const int management_panel_button = 2131034165;
			
			// aapt resource value: 0x7f050055
			public const int monitoring_button = 2131034197;
			
			// aapt resource value: 0x7f05000b
			public const int new_tape = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int new_tape_add = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int new_tape_goal = 2131034124;
			
			// aapt resource value: 0x7f05002f
			public const int new_tape_item_layout = 2131034159;
			
			// aapt resource value: 0x7f05000a
			public const int new_tape_layout = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int new_tape_ready_button = 2131034126;
			
			// aapt resource value: 0x7f050032
			public const int nti_delete_button = 2131034162;
			
			// aapt resource value: 0x7f050030
			public const int nti_frame = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int nti_image = 2131034161;
			
			// aapt resource value: 0x7f050036
			public const int our_kids_label = 2131034166;
			
			// aapt resource value: 0x7f05007a
			public const int patronymic_name_edit = 2131034234;
			
			// aapt resource value: 0x7f05006d
			public const int primerdivisor = 2131034221;
			
			// aapt resource value: 0x7f050034
			public const int relativeLayout1 = 2131034164;
			
			// aapt resource value: 0x7f05004b
			public const int return_schedule_button = 2131034187;
			
			// aapt resource value: 0x7f05005b
			public const int start_date = 2131034203;
			
			// aapt resource value: 0x7f05005a
			public const int start_date_label = 2131034202;
			
			// aapt resource value: 0x7f050059
			public const int start_date_layout = 2131034201;
			
			// aapt resource value: 0x7f05005c
			public const int start_time = 2131034204;
			
			// aapt resource value: 0x7f05004d
			public const int static_goal_card = 2131034189;
			
			// aapt resource value: 0x7f05004c
			public const int static_goal_card_frame = 2131034188;
			
			// aapt resource value: 0x7f050045
			public const int tape_control = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int tape_edit_button = 2131034182;
			
			// aapt resource value: 0x7f05004a
			public const int tape_info = 2131034186;
			
			// aapt resource value: 0x7f050049
			public const int tape_info_layout = 2131034185;
			
			// aapt resource value: 0x7f05004f
			public const int tape_item_frame = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int tape_item_image = 2131034192;
			
			// aapt resource value: 0x7f05004e
			public const int tape_item_layout = 2131034190;
			
			// aapt resource value: 0x7f050048
			public const int tape_item_list = 2131034184;
			
			// aapt resource value: 0x7f050042
			public const int tape_main_layout = 2131034178;
			
			// aapt resource value: 0x7f050044
			public const int tape_user_image = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int tape_user_name = 2131034179;
			
			// aapt resource value: 0x7f05001a
			public const int textView1 = 2131034138;
			
			// aapt resource value: 0x7f05003f
			public const int textView2 = 2131034175;
			
			// aapt resource value: 0x7f050080
			public const int timetable_button = 2131034240;
			
			// aapt resource value: 0x7f05003e
			public const int timetable_info_layout = 2131034174;
			
			// aapt resource value: 0x7f050033
			public const int timetable_main_layout = 2131034163;
			
			// aapt resource value: 0x7f05003d
			public const int timetable_tape_layout = 2131034173;
			
			// aapt resource value: 0x7f05003c
			public const int timetable_tape_scroll = 2131034172;
			
			// aapt resource value: 0x7f05003b
			public const int top_bar_divider = 2131034171;
			
			// aapt resource value: 0x7f05002e
			public const int trip_detailed_info = 2131034158;
			
			// aapt resource value: 0x7f050051
			public const int trip_details = 2131034193;
			
			// aapt resource value: 0x7f050057
			public const int trip_details_edit = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int trip_edit_label = 2131034200;
			
			// aapt resource value: 0x7f050054
			public const int trip_end_date = 2131034196;
			
			// aapt resource value: 0x7f050019
			public const int trip_list = 2131034137;
			
			// aapt resource value: 0x7f05002d
			public const int trip_list_frame = 2131034157;
			
			// aapt resource value: 0x7f050064
			public const int trip_list_item = 2131034212;
			
			// aapt resource value: 0x7f050052
			public const int trip_number = 2131034194;
			
			// aapt resource value: 0x7f05001c
			public const int trip_recycler_view = 2131034140;
			
			// aapt resource value: 0x7f050053
			public const int trip_start_date = 2131034195;
			
			// aapt resource value: 0x7f05002b
			public const int trips_divider = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int trips_label = 2131034154;
			
			// aapt resource value: 0x7f050027
			public const int user_card_divider = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int user_card_label = 2131034150;
			
			// aapt resource value: 0x7f050029
			public const int user_details = 2131034153;
			
			// aapt resource value: 0x7f05006b
			public const int user_details_age = 2131034219;
			
			// aapt resource value: 0x7f050028
			public const int user_details_and_trips = 2131034152;
			
			// aapt resource value: 0x7f05006c
			public const int user_details_birth = 2131034220;
			
			// aapt resource value: 0x7f050069
			public const int user_details_first_name = 2131034217;
			
			// aapt resource value: 0x7f05006f
			public const int user_details_fragment = 2131034223;
			
			// aapt resource value: 0x7f050025
			public const int user_details_general = 2131034149;
			
			// aapt resource value: 0x7f050068
			public const int user_details_last_name = 2131034216;
			
			// aapt resource value: 0x7f05006a
			public const int user_details_patronymic_name = 2131034218;
			
			// aapt resource value: 0x7f050066
			public const int user_details_photo = 2131034214;
			
			// aapt resource value: 0x7f050074
			public const int user_details_photo_frame = 2131034228;
			
			// aapt resource value: 0x7f050087
			public const int user_fpname = 2131034247;
			
			// aapt resource value: 0x7f050086
			public const int user_lastname = 2131034246;
			
			// aapt resource value: 0x7f050023
			public const int user_list = 2131034147;
			
			// aapt resource value: 0x7f050081
			public const int user_list_main_content = 2131034241;
			
			// aapt resource value: 0x7f050084
			public const int user_list_photo_frame = 2131034244;
			
			// aapt resource value: 0x7f050085
			public const int user_photo = 2131034245;
			
			// aapt resource value: 0x7f05007f
			public const int user_recycler_view = 2131034239;
			
			// aapt resource value: 0x7f05002c
			public const int user_trips = 2131034156;
			
			// aapt resource value: 0x7f050047
			public const int view1 = 2131034183;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int card_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int create_timetable = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int error_message = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hospital_trip_list = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int info = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int info_message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int management = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int new_tape_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int timetable = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int timetable_tape = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int timetable_tape_item = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int trip_details = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int trip_details_edit = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int trip_list_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int user_details = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int user_details_edit = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int user_list = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int user_list_item = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int card_popup_menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int hospital_trip_popup_menu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int user_popup_menu = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06003e
			public const int activities = 2131099710;
			
			// aapt resource value: 0x7f060009
			public const int add_button = 2131099657;
			
			// aapt resource value: 0x7f060041
			public const int add_card = 2131099713;
			
			// aapt resource value: 0x7f060013
			public const int add_photo = 2131099667;
			
			// aapt resource value: 0x7f06002a
			public const int add_trip = 2131099690;
			
			// aapt resource value: 0x7f06001d
			public const int add_user_profile = 2131099677;
			
			// aapt resource value: 0x7f060031
			public const int adding_trip = 2131099697;
			
			// aapt resource value: 0x7f060042
			public const int all_done = 2131099714;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int cancel_button = 2131099660;
			
			// aapt resource value: 0x7f060023
			public const int card_is_used = 2131099683;
			
			// aapt resource value: 0x7f060012
			public const int change_photo = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int choose_from_gallery = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int choose_photo = 2131099668;
			
			// aapt resource value: 0x7f060033
			public const int choose_trip_end_date = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int choose_trip_start_date = 2131099698;
			
			// aapt resource value: 0x7f06003d
			public const int creating_timetable_for = 2131099709;
			
			// aapt resource value: 0x7f06000a
			public const int delete_button = 2131099658;
			
			// aapt resource value: 0x7f06001c
			public const int delete_card = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int delete_trip = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int delete_user = 2131099674;
			
			// aapt resource value: 0x7f060026
			public const int detailed_trip_info = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int detailed_user_info = 2131099685;
			
			// aapt resource value: 0x7f06000b
			public const int edit_button = 2131099659;
			
			// aapt resource value: 0x7f060030
			public const int edit_trip = 2131099696;
			
			// aapt resource value: 0x7f060029
			public const int empty_trip_list = 2131099689;
			
			// aapt resource value: 0x7f060024
			public const int empty_user_list = 2131099684;
			
			// aapt resource value: 0x7f06000e
			public const int enter_first_name = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int enter_kid_date = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int enter_last_name = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int enter_patronymic_name = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int general_monitoring_button = 2131099649;
			
			// aapt resource value: 0x7f06003b
			public const int go_and_add = 2131099707;
			
			// aapt resource value: 0x7f06003f
			public const int goals = 2131099711;
			
			// aapt resource value: 0x7f060027
			public const int kids_list = 2131099687;
			
			// aapt resource value: 0x7f060002
			public const int monitoring_button = 2131099650;
			
			// aapt resource value: 0x7f060040
			public const int motivation_goals = 2131099712;
			
			// aapt resource value: 0x7f06002f
			public const int new_trip = 2131099695;
			
			// aapt resource value: 0x7f06003c
			public const int no_timetable_for_today = 2131099708;
			
			// aapt resource value: 0x7f060039
			public const int no_users_for_current_date = 2131099705;
			
			// aapt resource value: 0x7f06000d
			public const int ok_button = 2131099661;
			
			// aapt resource value: 0x7f060034
			public const int our_kids = 2131099700;
			
			// aapt resource value: 0x7f060022
			public const int present_trip = 2131099682;
			
			// aapt resource value: 0x7f060037
			public const int return_completed_schedule = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int schedule_is_completed = 2131099704;
			
			// aapt resource value: 0x7f060036
			public const int screen_is_locked = 2131099702;
			
			// aapt resource value: 0x7f060020
			public const int sure_to_delete_card = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int sure_to_delete_trip = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int sure_to_delete_user = 2131099678;
			
			// aapt resource value: 0x7f060015
			public const int take_a_photo = 2131099669;
			
			// aapt resource value: 0x7f060035
			public const int timetable_for_the_day = 2131099701;
			
			// aapt resource value: 0x7f06003a
			public const int to_start_working_with_timetable = 2131099706;
			
			// aapt resource value: 0x7f060018
			public const int trip_data_not_set = 2131099672;
			
			// aapt resource value: 0x7f06002e
			public const int trip_finish_date = 2131099694;
			
			// aapt resource value: 0x7f06002b
			public const int trip_in_list = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int trip_start_date = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int trips = 2131099692;
			
			// aapt resource value: 0x7f060028
			public const int trips_list = 2131099688;
			
			// aapt resource value: 0x7f060008
			public const int user_card = 2131099656;
			
			// aapt resource value: 0x7f060017
			public const int user_data_not_set = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int user_details_age = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int user_details_birth = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int user_details_first_name = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int user_details_last_name = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int user_details_patronymic_name = 2131099653;
			
			// aapt resource value: 0x7f060021
			public const int user_in_present_timetable = 2131099681;
			
			// aapt resource value: 0x7f060019
			public const int user_photo_not_set = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
