#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InteractiveTimetable.Droid.Resource", IsApplication=true)]

namespace InteractiveTimetable.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_photo_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050023
			public const int apply_changes_btn = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int birth_date_edit = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int birth_date_show = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int cancel_btn = 2131034148;
			
			// aapt resource value: 0x7f05001b
			public const int edit_photo_btn = 2131034139;
			
			// aapt resource value: 0x7f05000c
			public const int edit_user = 2131034124;
			
			// aapt resource value: 0x7f050025
			public const int find_user = 2131034149;
			
			// aapt resource value: 0x7f05001f
			public const int first_name_edit = 2131034143;
			
			// aapt resource value: 0x7f050014
			public const int frameLayout1 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int frameLayout2 = 2131034133;
			
			// aapt resource value: 0x7f05000a
			public const int frameLayout3 = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int general_monitoring = 2131034131;
			
			// aapt resource value: 0x7f05001d
			public const int gridLayout1 = 2131034141;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05001e
			public const int last_name_edit = 2131034142;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int linearLayout2 = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int linearLayout3 = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout4 = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int linearLayout5 = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int linearLayout6 = 2131034136;
			
			// aapt resource value: 0x7f050003
			public const int main_landscape = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int main_portait = 2131034113;
			
			// aapt resource value: 0x7f050020
			public const int patronymic_name_edit = 2131034144;
			
			// aapt resource value: 0x7f050012
			public const int primerdivisor = 2131034130;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int textView2 = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int user_details = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int user_details_age = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int user_details_birth = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int user_details_first_name = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int user_details_general = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int user_details_last_name = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int user_details_patronymic_name = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int user_details_photo = 2131034123;
			
			// aapt resource value: 0x7f050019
			public const int user_details_photo_frame = 2131034137;
			
			// aapt resource value: 0x7f05002a
			public const int user_fpname = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int user_lastname = 2131034153;
			
			// aapt resource value: 0x7f050002
			public const int user_list = 2131034114;
			
			// aapt resource value: 0x7f050027
			public const int user_list_photo_frame = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int user_photo = 2131034152;
			
			// aapt resource value: 0x7f050026
			public const int user_recycler_view = 2131034150;
			
			// aapt resource value: 0x7f050008
			public const int user_trips = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int management = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int user_details = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int user_details_edit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int user_list = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int user_list_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060009
			public const int add_button = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int add_photo = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int cancel_button = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int change_photo = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int edit_button = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int enter_first_name = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int enter_kid_date = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int enter_last_name = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int enter_patronymic_name = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int general_monitoring_button = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int user_card = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int user_details_age = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int user_details_birth = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int user_details_first_name = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int user_details_last_name = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int user_details_patronymic_name = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
